services:
  playwright:
    build: .
    image: playwright-image:local
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CI=true
    env_file:
      - .env
    command: >
      sh -c "npx playwright test --project='API-Tests' --project='UI-Chromium' && npm run report:generate"
