name: Playwright Tests

on:
  push:
    branches: [main, fix/ci-allure]

  pull_request:
    branches: [main]

  workflow_dispatch:
    inputs:
      test_type:
        description: 'What to execute?'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - ui-all
          - ui-chromium
          - ui-firefox
          - ui-webKit
          - api

jobs:
  testing:
    timeout-minutes: 100
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ vars.API_URL }}
      API_KEY: ${{ secrets.API_KEY }}
      BASE_URL: ${{ vars.BASE_URL }}
      USER_NAME: ${{ secrets.USER_NAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup Java (Necessário para Allure)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run API
        if: github.event_name != 'workflow_dispatch'
        run: npx playwright test --project="API-Tests" || true

      - name: Run all tests
        if: github.event.inputs.test_type == 'all'
        run: npx playwright test || true

      - name: Run API + Chromium (default) tests
        if: github.event.inputs.test_type == 'default'
        run: npx playwright test --project="API-Tests" --project="UI-Chromium" || true

      - name: Run UI Chromium
        if: github.event.inputs.test_type == 'ui-chromium'
        run: npx playwright test --project="UI-Chromium" || true

      - name: Run UI Firefox
        if: github.event.inputs.test_type == 'ui-firefox'
        run: npx playwright test --project="UI-Firefox" || true

      - name: Run UI WebKit
        if: github.event.inputs.test_type == 'ui-webKit'
        run: npx playwright test --project="UI-WebKit" || true

      - name: Run all UI browsers
        if: github.event.inputs.test_type == 'ui-all'
        run: npx playwright test --project="UI-Chromium" --project="UI-Firefox" --project="UI-WebKit" || true

      - name: Generate Allure Report
        if: always()
        run: npm run report:generate

      - name: Upload Allure
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report
          retention-days: 7

      - name: Upload Playwright Trace/Videos (On Failure)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-traces
          path: test-results/
          retention-days: 7
