name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  api-testing:
    timeout-minutes: 40
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test --project='API-Tests' --project='UI-Chromium' || true
        env:
          API_URL: ${{ vars.API_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          BASE_URL: ${{ vars.BASE_URL }}
          USERNAME: ${{ secrets.USER_NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
      - name: Generate Allure Report
        run: npm run report:generate

      - name: Upload Allure Results (Raw Data)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 7

      - name: Upload Allure Dashboard (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-dashboard
          path: allure-report
          retention-days: 7

      - name: Upload Playwright Trace/Videos (On Failure)
        uses: actions/upload-artifact@v4
        if: failure() # Só sobe se algo falhar, para poupar espaço
        with:
          name: playwright-traces
          path: test-results/
          retention-days: 7
